version: '2.1'
services:
  
#eureka server

  eureka-server:
    build: eureka-server/
    image: eureka-server
    container_name: eureka-server
    network_mode: "host"
    hostname: localhost
    ports:
      - 8761:8761
    restart: always
    healthcheck:
      test: "exit 0"
    
#config server
    
  config-service:
    build: config-service/
    image: config-server
    container_name: config-server
    network_mode: "host"
    hostname: localhost
    ports:
      - 8891:8891
    restart: always
    healthcheck:
      test: "exit 0"

#api gateway

  api-gateway:
    build: zuul-apigateway/
    image: api-gateway
    container_name: api-gateway
    network_mode: "host"
    hostname: localhost
    ports:
      - 8080:8080
    depends_on:
      config-service:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    restart: always
    healthcheck:
      test: "exit 0"

