version: '2.1'
services:

#userlogin microservice

  user-login:
    build: user-login/
    image: user-auth
    container_name: user-login
    network_mode: "host"
    hostname: localhost
    ports:
      - 8082:8082
#    depends_on:
#      eureka-server:
#        condition: service_healthy
#      mysql-database:
#        condition: service_healthy
    restart: always
    healthcheck:
      test: "exit 0"

#userprofile microservice
        
  user-profile:
    build: user-profile/
    image: user-profile
    container_name: user-profile
    network_mode: "host"
    hostname: localhost
    ports:
      - 8070:8070
#    depends_on:
#      eureka-server:
#        condition: service_healthy
#      mongo-database:
#        condition: service_healthy
    restart: always
    healthcheck:
      test: "exit 0"
        
#bookservice microservice
        
  book-service:
    build: book-service/
    image: book-service
    container_name: book-service
    network_mode: "host"
    hostname: localhost
    ports:
      - 8888:8888
#    depends_on:
#      eureka-server:
#        condition: service_healthy
#      mongo-database:
#        condition: service_healthy
    restart: always
    healthcheck:
      test: "exit 0"
        
#recommendation microservice
        
  recommendation:
    build: recommendation/
    image: recommendation
    container_name: recommendation
    network_mode: "host"
    hostname: localhost
    ports:
      - 8092:8092
#    depends_on:
#      eureka-server:
#        condition: service_healthy
#      neo4j-database:
#        condition: service_healthy
    restart: always
    healthcheck:
      test: "exit 0" 
        
