# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['127.0.0.1:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['127.0.0.1:3000']

  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['127.0.0.1:8761']

  - job_name: 'apigateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['127.0.0.1:8080']
    
  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['127.0.0.1:8891']

#  - job_name: 'user-profile'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 5s
#    static_configs:
#    - targets: ['127.0.0.1:8070'] 
#
#  - job_name: 'book-service'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 5s
#    static_configs:
#    - targets: ['127.0.0.1:8888']
#
#  - job_name: 'recommendation'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 5s
#    static_configs:
#    - targets: ['127.0.0.1:8092']
#
#  - job_name: 'user-login'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 5s
#    static_configs:
#    - targets: ['127.0.0.1:8082']
#    
