spring:
  application:
    name: userprofile
  data:
    mongodb:
      database: userprofile
      host: localhost
      port: "27017"
      uri: mongodb://localhost/userprofile
      username: ""
server:
  port: "8070"
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
