spring:
 application:
   name: user-login
 datasource:
   url: jdbc:mysql://user-sql:3306/go_d?useSSL=false
   username: root
   password: 
   driver-class-name: com.mysql.jdbc.Driver
 jpa:
   hibernate:
     ddl-auto: create
   database-platform: org.hibernate.dialect.MySQL5Dialect
   generate-ddl: "true"
   show-sql: "true"
server:
 port: "8082"
eureka:
 client:
   register-with-eureka: "true"
   fetch-registry: "true"
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/
