server:
  port: 8070
spring:
  application:
    name: userprofile
#  data:
#    mongodb:
#      database: userprofile
#      host: localhost
#      port: "27017"
#      uri: mongodb://localhost/userprofile
#      username: ""
#eureka:
#  client:
#    register-with-eureka: "true"
#    fetch-registry: "true"
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
